#!/usr/bin/python2
import serenoa.core
import argparse

parser = argparse.ArgumentParser(description='Create and deploy static web sites')
parser.add_argument('path', metavar='PATH', type=str,
                   help='Path to the root directory of the site')
parser.add_argument('-s', dest='serve', type=int,
                   help='Run a server on the specified port')
parser.add_argument('-l', dest='list', action='store_true',
                   help='List the files in the site')

args = parser.parse_args()

context = serenoa.core.Context(args.path)
context.run()

if args.list:
	for file in context.files:
		print(file)
elif args.serve:
	import serenoa.server
	serenoa.server.serve(context, args.serve)
else:
	print("Error: nothing to do")